# NOTE: ensure directories exist, aria2c will fail otherwise

# Disk
dir             			= ${HOME}/dl/aria2
disk-cache      			= 256M
file-allocation 			= none

# Download
continue                    = true
always-resume               = true
split                       = 16
min-split-size              = 1M
max-tries                   = 10
max-connection-per-server   = 16
max-concurrent-downloads    = 8
timeout                     = 600
user-agent                  = Transmission/2.77

# RPC
enable-rpc                  = true
rpc-listen-port             = 6800
rpc-listen-all              = false
rpc-secret                  = aria

# BT
follow-torrent              = true
enable-dht                  = true
dht-listen-port             = 6881-6999
dht-file-path               = ${HOME}/.cache/aria2/dht.dat
dht-entry-point             = dht.transmissionbt.com:6881
bt-max-peers                = 100
bt-enable-lpd               = true
bt-request-peer-speed-limit = 10M
bt-tracker-interval         = 0
enable-peer-exchange        = true
peer-id-prefix              = -TR2770-
peer-agent                  = Transmission/2.77
seed-ratio                  = 0
seed-time                   = 0
allow-overwrite             = true
bt-tracker                  = udp://tracker.opentrackr.org:1337/announce,udp://open.tracker.cl:1337/announce,udp://tracker.openbittorrent.com:6969/announce,udp://exodus.desync.com:6969/announce,udp://open.stealth.si:80/announce,udp://tracker.torrent.eu.org:451/announce,udp://tracker.moeking.me:6969/announce,udp://tracker.tiny-vps.com:6969/announce,udp://tracker.cyberia.is:6969/announce,udp://bt1.archive.org:6969/announce,udp://bt2.archive.org:6969/announce
