#!/bin/sh
# Color picker using imagemagick

[ "$WAYLAND_DISPLAY" ] || exit 1

color=$(grim -g "$(slurp -b 00000000 -p)" -t png - | \
  magick - -format '%[hex:p{0,0}]' info:-)

[ "$color" ] && {
    printf "#%s" "$color" | wl-copy
    notify-send "Picked color" \
        "<span color='#$color'></span> #$color copied to clipboard"
    echo "#$color"
}
