#!/usr/bin/env dash
# Color picker using niri ipc
# Color preview requires `imagemagick`

command -v magick >/dev/null || {
    printf "'imagemagick' not installed\n"
    exit 1
}

output=$(niri msg pick-color)
color=${output##*Hex: }

[ "$color" ] && {
    printf "%s" "$color" | wl-copy
    printf "%s\n" "$color"
    prev="$(mktemp -u).png"
    trap 'rm -f "$prev"' EXIT
    magick convert -size 24x24 "xc:$color" "$prev" && icon="$prev" || icon=""
    notify-send ${icon:+-i "$icon"} "Picked color" "$color copied to clipboard"
}
