#!/bin/sh
# Tiny POSIX compliant fetch script
# Requires nerdfont to display icons

# Colors
colorise() { 
    color="\033[31m" # red
    printf "%b" "${color}${1}\033[0m"
}

# Title
title() {
    title="${USER:-$(whoami)}@$(hostname)"
}

# Distribution and package count
distro() {
    [ -f /etc/os-release ] && . /etc/os-release
    os="$(printf "%s" "${PRETTY_NAME:-Linux}" | tr '[:upper:]' '[:lower:]')"
    case "$os" in
        *void*) pkg="$(xbps-query -l | wc -l) (xbps)" ;;
        *kiss*) pkg="$(ls /var/db/kiss/installed | wc -l) (kiss)" ;;
        *) pkg="0 (unknown)" ;;
    esac
}

# Window manager
wm() {
    wmname=$(printf "%s" "${XDG_CURRENT_DESKTOP:-unknown}" | 
        tr '[:upper:]' '[:lower:]')
}

# Kernel
kernel () {
    read -r _ _ kernel _ < /proc/version
}

# Shell
shell() {
    shell=${SHELL##*/}
}

# Uptime
uptime() {
    u=$(cut -d' ' -f1 /proc/uptime); u=${u%.*}
    d=$(( u/86400)); h=$((u/3600%24)); m=$((u/60%60))
    [ "$d" -ge 1 ] && uptime="${d}d "
    [ "$h" -ge 1 ] && uptime="${uptime}${h}h "
    uptime="${uptime}${m}m"
}

# Memory
memory() {
    u=0; t=0
    while IFS=: read -r a b; do
        b=${b% kB}
        case $a in
            MemTotal) t=$b; u=$b ;;
            Shmem) u=$((u + b)) ;;
            MemFree|Buffers|Cached|SReclaimable) u=$((u - b)) ;;
        esac
    done </proc/meminfo
    u=$((u / 1024)); t=$((t / 1024))
    memory="${u}MiB / ${t}MiB"
}

# Storage
disk() {
    set -- $(df -P "${disk_show:-/}" | awk 'NR==2{print $3,$2}')
    used=$1; total=$2
    perc=$((used * 100 / total))
    used=$((used / 1024 / 1024))
    total=$((total / 1024 / 1024))
    disk="${used}GiB / ${total}GiB (${perc}%)"
}

# Colors
colors() {
    i=0
    while [ "$i" -lt 8 ]; do
        palette="${palette}\033[48;5;${i}m   \033[0m"
        i=$((i+1))
    done
}

{
    title
    wm
    distro # 
    kernel #  󰏖
    shell # 
    # uptime # 
    memory # 
    disk # 󰋊
    colors # 󰏘
} >/dev/null

# Output
printf "%b\n" "               $title
               $(colorise )  $os ${wmname:+- $wmname}
   (\\\ /)       $(colorise )  $kernel
   ( . .)      $(colorise )  $shell
   c(\")(\")     $(colorise 󰏖)  $memory
               $(colorise 󰏘)  $palette"

# printf "%b\n" "                  $title
#    /| ､           $(colorise )  $os ${wmname:+- $wmname}
#   (°､ ｡ 7         $(colorise )  $kernel
#    |､  ~ヽ        $(colorise )  $shell
#    じしf_,)       $(colorise 󰏖)  $package
#                   $(colorise 󰏘)  $palette"
