#!/bin/sh
# Dedicated gamescope session with Bottles

export ENABLE_GAMESCOPE_WSI=1
export SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0
export vk_xwayland_wait_ready=false
export INTEL_DEBUG=norbc
export mesa_glthread=true

: "${SCREEN_WIDTH:=1920}"
: "${SCREEN_HEIGHT:=1080}"
: "${REFRESH:=120}"

exec gamescope \
    -W "$SCREEN_WIDTH" -H "$SCREEN_HEIGHT" \
    -w "$SCREEN_WIDTH" -h "$SCREEN_HEIGHT" \
    -r "$REFRESH" \
	--hdr-enabled \
    --adaptive-sync \
    ${WAYLAND_DISPLAY:+--backend wayland} \
    # -- "${@:-flatpak run page.kramo.Cartridges}"
