#!/bin/sh
# Logout menu
# Requires 'permit nopass :wheel' in /etc/doas.conf

opt=$(printf "Poweroff\nReboot\nSleep\nConservation mode - On\nConservation mode - Off" |
    fuzzel -dp "Power opts: ")

case "$opt" in
    "Poweroff") loginctl poweroff ;;
    "Reboot") loginctl reboot ;;
    "Sleep") loginctl suspend ;;
    "Conservation mode - On")  printf 1 |
        doas tee /sys/bus/platform/devices/VPC2004:*/conservation_mode ;;
    "Conservation mode - Off") printf 0 |
        doas tee /sys/bus/platform/devices/VPC2004:*/conservation_mode ;;
    *) exit 1 ;;
esac

[ "$opt" ] && notify-send "$opt"
