#!/usr/bin/env dash
# Logout menu

opt=$(printf "Shutdown\nReboot\nSleep\nLock\nPower off monitors\nStop auto-sleep\nStart auto-sleep\nEnable conservation mode (lenovo only)\nDisable conservation mode (lenovo only)" |
    fuzzel -dp "Power options: ")

case "$opt" in
    "Shutdown") loginctl poweroff || systemctl poweroff ;;
    "Reboot") loginctl reboot || systemctl reboot ;;
    "Sleep") loginctl suspend || systemctl suspend ;;
    "Lock") swaylock -f ;;
    "Power off monitors") niri msg action power-off-monitors ;;
    "Stop auto-sleep") dinitctl stop swayidle ;;
    "Start auto-sleep") dinitctl start swayidle ;;
    "Enable conservation mode (lenovo only)") printf 1 | doas tee /sys/bus/platform/devices/VPC2004:*/conservation_mode ;;
    "Disable conservation mode (lenovo only)") printf 0 | doas tee /sys/bus/platform/devices/VPC2004:*/conservation_mode ;;
    *) exit 1 ;;
esac

[ "$opt" ] && notify-send "$opt"
