#!/bin/sh
# Menu to interact with media
# Requires `playerctl`

opt=$(printf "Play/Pause playback\nStop playback\nPrevious song\nNext song" |
    fuzzel -dp "Select media action: ")

case "$opt" in
    "Play/Pause playback") playerctl play-pause ;;
    "Stop playback") playerctl stop ;;
    "Next song") playerctl next ;;
    "Previous song") playerctl previous ;;
    *) exit 1 ;;
esac
