#!/bin/sh
# Notify on MPD song change
# shellcheck disable=SC2154

music="$HOME/music" temp="/tmp/mpd" art="$temp/albumart.jpg"
mkdir -p "$temp"; old=$(mpc current)

while :; do
    mpc idle player >/dev/null
    new=$(mpc current)
    [ -z "$new" ] || [ "$new" = "$old" ] && continue
    old=$new
    rm -f "$art"
    for i in file artist title album; do
        eval "$i=\$(mpc current -f '%$i%')"
    done
    mpc readpicture "$music/$file" > "$art"
    notify-send -a "music" "$title • $artist" "$album" --icon="$art"
done
