#!/bin/sh
# Screenshot utility

usage() {
    printf "usage: %s [-a|-f] [-o output] [-s output-file]\n" "${0##*/}"
    exit 1
}

while getopts "o:afsh" arg; do case $arg in
    o) out="$OPTARG" ;;
    a) sel="$(wfreeze slurp)" ;;
    f) full=1 ;;
    s) save=1 ;;
    *) usage ;;
esac; done
shift $((OPTIND-1))

[ -z "$sel" ] && [ -z "$full" ] && usage

[ "$save" ] && {
    dir=${XDG_PICTURES_DIR:-"$HOME/pics"}; mkdir -p "$dir"
    : "${file:=${1:-$dir/screenshots/$(date +%F-%T).png}}"
    msg="Saved to <b>${file##*/}</b>"
}

grim ${out:+-o "$out"} ${sel:+-g "$sel"} ${full:+} "${file:-/tmp/ss.png}"
wl-copy -t image/png < "${file:-/tmp/ss.png}"
notify-send "Screenshot taken!" "${msg:-Copied to clipboard}"
