#!/bin/sh
# Screen recording utility
# Requires `wl-screenrec` and `jq`

usage() {
    printf "usage: %s [-f filename] [-o output (display)] [-r]\n" "${0##*/}"
    exit 1
}

while getopts "ro:f:" arg; do case $arg in
    r) region=$(slurp) || exit 1 ;;
    o) output="$OPTARG" ;;
    f) filename="$OPTARG" ;;
    *) usage ;;
esac; done
shift $((OPTIND-1))

dir="${XDG_VIDEOS_DIR:-$HOME/vids}/recs"; mkdir -p "$dir"
: "${filename:=$dir/$(date +%F-%T).mp4}"
: "${output:=$(niri msg -j focused-output | jq -r '.name')}"

wl-screenrec ${output:+-o "$output"} ${region:+-g "$region"} -f "$filename" &
notify-send "Recording started" "${filename##*/}"
