#!/bin/sh
# Menu to interact with 'theme'

opt=$(printf "Reapply wallpaper\nPrevious wallpaper\nClear wallpaper\nColorscheme\nRandom wallpaper\nWallpaper menu\nWallpaper history menu\nColor picker\nToggle waybar visibility" |
    fuzzel -dp "Select action: ")

case "$opt" in
    "Reapply wallpaper") theme -r ;;
    "Previous wallpaper") theme -p ;;
    "Clear wallpaper") swww clear ;;
    "Colorscheme") theme -c ;;
    "Random wallpaper") theme -s ;;
    "Wallpaper menu") theme -m ;;
    "Wallpaper history menu") theme -h ;;
    "Color picker") colorpick ;;
    "Toggle waybar visibility") pkill -SIGUSR1 waybar ;;
    *) exit 1 ;;
esac
