#!/bin/sh
# Set wallpaper, colorscheme and generate backdrop
# Backdrop generation requires `graphicsmagick`
# Colorscheme setting requires `reclr`
# Wallpaper setting requires `awww`
# Wallpaper menu requires `chafa and `fzf`

dir="${XDG_PICTURES_DIR:-$HOME/pics}/walls"
hist="${XDG_CACHE_HOME:-$HOME/.cache}/script-cache/wallpaper-history"
info="${XDG_CACHE_HOME:-$HOME/.cache}/script-cache/theme"
backdrop_cache="${XDG_CACHE_HOME:-$HOME/.cache}/script-cache/backdrop.png"

[ -f "$info" ] && . "$info" || : > "$info"

usage() {
    cat >&2 <<- EOF
	usage: ${0##*/} [-rpsmhc]
	  -r    reapply current wallpaper
	  -p    apply previous wallpaper
	  -s    apply random wallpaper
	  -m    select wallpaper from menu
	  -h    select wallpaper from history
	  -c    select colorscheme
	EOF
    exit 1
}

save() {
    printf 'prev_wall="%s"\ncur_wall="%s"\ncolorscheme="%s"\n' \
        "$prev_wall" "$cur_wall" "$colorscheme" > "$info"
    printf '%s\n%s' "$cur_wall" "$(head -n 49 "$hist")" > "$hist"
}

colors() {
    reclr -i "$1"
    colorscheme=$1
    save
    command -v makoctl > /dev/null && makoctl reload
    command -v fnott > /dev/null && dinitctl restart fnott
    notify-send -a theme "Colorscheme set!" \
        "Colorscheme set to <b>$colorscheme</b>"
    command -v waybar > /dev/null && killall -SIGUSR2 waybar
    command -v spicetify > /dev/null && spicetify apply
}

backdrop() {
    gm convert "$1" \
        -scale 25% \
        -blur 0x3 \
        -quality 50 \
        "$backdrop_cache"
    awww img \
        --transition-type fade \
        --transition-duration 0.75 \
        -n backdrop \
        "$backdrop_cache"
}

wall() {
    [ "$1" ] || exit 1
    awww img \
        --transition-type outer \
        --transition-step 125 \
        --transition-duration 1 \
        --transition-fps 60 \
        "$1"
    backdrop "$1" &
    [ "$arg" != "r" ] && {
        prev_wall=$cur_wall cur_wall=$1
        save
        notify-send -a theme "Wallpaper set!" \
            "Wallpaper set to <b>${cur_wall##*/}</b>"
    }
}

strip_prefix() {
    while read -r f; do
        printf '%s\n' "${f#"$1/"}"
    done
}

menu() {
    while true; do
        sel=$(find "$dir" -type f -iregex '.*\.\(png\|jpe\?g\|gif\)' |
            fzf --prompt="select wallpaper: " \
                --layout=reverse --border \
                --header="enter: apply  ctrl-c/esc: quit" \
                --preview="chafa --work=1 --size=\${FZF_PREVIEW_COLUMNS}x\${FZF_PREVIEW_LINES} {}" \
                --preview-window=right:50%:wrap)
        [ $? -ne 0 ] && break

        [ "$sel" ] && {
            printf 'Setting \033[34m%s\033[0m as wallpaper...\n' "${sel##*/}"
            wall "$sel"
        }
    done
}

[ "$1" = "_menu" ] && { menu; exit; }

[ $# -eq 0 ] && usage
while getopts rpsmhc arg; do case $arg in
    r) wall "$cur_wall" ;;
    p) wall "$prev_wall" ;;
    m) foot -T "wallpaper-menu" --window-size-pixels=1000x400 -e "$0" _menu ;;
    s)
        wall "$(find "$dir" -type f -iregex '.*\.\(png\|jpe\?g\|gif\)' |
            sort -R | sed 1q)"
        ;;
    h)
        sel=$(strip_prefix "$dir" < "$hist" |
            awk '!seen[$0]++' | fuzzel -dp 'Select wallpaper: ')
        [ "$sel" ] && wall "$dir/$sel"
        ;;
    c)
        sel=$(reclr -l | fuzzel -dp 'Select colorscheme: ')
        [ "$sel" ] && colors "$sel"
        ;;
    *) usage ;;
esac done
