#!/bin/sh
# Set wallpaper, colorscheme and generate backdrop
# Backdrop generation requires `graphicsmagick`
# Colorscheme setting requires `reclr`
# Wallpaper setting requires `swww`

dir="${XDG_PICTURES_DIR:-$HOME/pics}/walls"
hist="${XDG_CACHE_HOME:-$HOME/.cache}/script-cache/wallpaper-history"
info="${XDG_CACHE_HOME:-$HOME/.cache}/script-cache/theme"
backdrop_cache="${XDG_CACHE_HOME:-$HOME/.cache}/script-cache/backdrop.png"

[ -f "$info" ] && . "$info" || : > "$info"

usage() {
    cat >&2 <<- EOF
	usage: ${0##*/} [-rpsmhc]
	  -r    reapply current wallpaper
	  -p    apply previous wallpaper
	  -s    apply random wallpaper
	  -m    select wallpaper from menu
	  -h    select wallpaper from history
	  -c    select colorscheme
	EOF
    exit 1
}

save() {
    printf 'prev_wall="%s"\ncur_wall="%s"\ncolorscheme="%s"\n' \
        "$prev_wall" "$cur_wall" "$colorscheme" > "$info"
    printf '%s\n%s' "$cur_wall" "$(head -n 49 "$hist")" > "$hist"
}

colors() {
    reclr -i "$1"
    colorscheme=$1
    save
    command -v makoctl > /dev/null && makoctl reload
    notify-send -a theme "Colorscheme set!" \
        "Colorscheme set to <b>$colorscheme</b>"
    command -v waybar > /dev/null && killall -SIGUSR2 waybar
    command -v spicetify > /dev/null && spicetify apply
}

backdrop() {
    gm convert "$1" \
        -scale 25% \
        -blur 0x3 \
        -quality 50 \
        "$backdrop_cache"
    swww img \
        --transition-type fade \
        --transition-duration 0.75 \
        -n backdrop \
        "$backdrop_cache"
}

wall() {
    [ "$1" ] || exit 1
    swww img \
        --transition-type outer \
        --transition-step 125 \
        --transition-duration 1 \
        --transition-fps 60 \
        "$1"
    backdrop "$1" &
    [ "$arg" != "r" ] && {
        prev_wall=$cur_wall cur_wall=$1
        save
        notify-send -a theme "Wallpaper set!" \
            "Wallpaper set to <b>${cur_wall##*/}</b>"
    }
}

strip_prefix() {
    while read -r f; do
        printf '%s\n' "${f#"$1/"}"
    done
}

[ $# -eq 0 ] && usage
while getopts rpsmhc arg; do case $arg in
    r) wall "$cur_wall" ;;
    p) wall "$prev_wall" ;;
    s)
        wall "$(find "$dir" -type f -iregex '.*\.\(png\|jpe\?g\|gif\)' |
            sort -R | sed 1q)"
        ;;
    m)
        sel=$(find "$dir" -type f -not -path '*/.git/*' |
            strip_prefix "$dir" | fuzzel -dp 'Select wallpaper: ')
        [ "$sel" ] && wall "$dir/$sel"
        ;;
    h)
        sel=$(strip_prefix "$dir" < "$hist" |
            awk '!seen[$0]++' | fuzzel -dp 'Select wallpaper: ')
        [ "$sel" ] && wall "$dir/$sel"
        ;;
    c)
        sel=$(reclr -l | fuzzel -dp 'Select colorscheme: ')
        [ "$sel" ] && colors "$sel"
        ;;
    *) usage ;;
esac done
