#!/bin/sh
# Volume control

max=1.5 # 1.5
case $1 in
    -t) wpctl set-mute @DEFAULT_SINK@ toggle ;;
    -i) op="+" ;;
    -d) op="-" ;;
    -s) op="" ;;
    *) printf "usage: %s [-t] [-i|-d|-s number]\n" "${0##*/}" >&2; exit 1 ;;
esac

[ "$2" ] && ! wpctl get-volume @DEFAULT_SINK@ | grep -q '\[MUTED\]' &&
    wpctl set-volume -l $max @DEFAULT_SINK@ "$2%$op"

vol="$(wpctl get-volume @DEFAULT_SINK@)" # Volume: 0.07
vol="${vol##*: }"                   # 0.07
[ "$vol" = "${vol##*\ }" ] && {     # 0.07 [MUTED] ?
    vol="${vol%%.*}${vol##*.}"      # 007
    disp="${vol#${vol%%[!0]*}}"     # 007 # 00
    disp="${disp:-0}%"              # ''  ? 0 + %
} || unset vol

[ "$DBUS_SESSION_BUS_ADDRESS" ] &&
    notify-send -a "volume" ${vol+-h int:value:$vol} "Volume: ${disp-muted}"
pkill -RTMIN+1 slstatus
