# Colorscheme
theme = "booberry-v2"

[editor]
line-number = "relative"     # use relative line numbers
bufferline = "multiple"      # only show when multiple buffers are open
color-modes = true           # colorise mode indicator
rulers = [80]                # conventional unix guideline
# default-yank-register="+"  # use system clipboard

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
C-s = ":w"
C-q = ":bclose"
C-tab = ":buffer-next"
C-space = "signature_help"
a = ["append_mode", "collapse_selection"]
F = ["select_all","select_regex"]

[keys.normal.space]
W = ":write"
q = ":quit"
Q = ":write-quit"
